---
title: "Midterm Code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
brands <- read.csv('data/brands.csv')
df <- read.csv('data/kijiji_data_fullset.csv')
```

```{r, warning=F, message=F}
library(dplyr)
library(ggplot2)
```

```{r}
# The dataframe seems to have many duplicates(multiple listings, problem with scraping?)
df <- distinct(df)
nrow(df)
```

```{r}
merged <- right_join(x=brands, y=df, 
by=c('brand', 'model', 'model_year'))
head(merged)
nrow(merged)
```
```{r}
# take important columns
merged <- merged %>% select(brand, model, model_year, Market.Price, list_price, condition, body_type, wheel_config, transmission, mileage)
```


```{r}
library(stringr)
merged$Market.Price <- str_remove_all(merged$Market.Price, "[$,]")
```

```{r, warning=F}
# N.A. values in Market Price indicate the site returned N.A, aka market price is unknown.
# cast N.A. values to NA as well
merged$Market.Price <- as.numeric(merged$Market.Price)
```

```{r}
# I'm 99% sure the market prices are in USD, when comparing to other sites like AutoTrader.net etc. so I will add a CAD market price column
conversion_rate <- 1.35
merged$Market.Price.CAD <- merged$Market.Price * conversion_rate
```

```{r}
# I think I will remove entries where listing price is 0. This is usually done on sites to show up first when customers sort by price, or sometimes price isn't listed. Either way, these people definitely aren't selling for free.
merged <- merged %>% filter(list_price != 0)
```

```{r}
# we have to remove rows with missing market values.
# we can't impute the data in any way because it's 2023 estimates, and market values should vary by year and stuff.
# no sensible way to impute.
merged <- merged %>% filter(!is.na(Market.Price.CAD))
nrow(merged)
```
```{r}
# further checks

# no more NA values
colSums(is.na(merged))

summary(merged)
```

```{r}
# we need to map 4x4 to AWD and '' to Other for
# wheel_config

merged = merged %>% mutate(wheel_config=case_when(
  wheel_config == '' ~ 'Other',
  wheel_config == 'Other' ~ 'Other',
  wheel_config == 'Front-wheel drive (FWD)' ~ 'FWD',
  wheel_config == 'Rear-wheel drive (RWD)' ~ 'RWD',
  TRUE ~ 'AWD'
))
```

```{r}
merged$transmission = ifelse(merged$transmission == '', 'Other', merged$transmission)
```




```{r}
# to create broader categories between cars i'll introduce a new categorical variable

ggplot(merged, aes(x=Market.Price.CAD)) +
  geom_histogram(bins=30)

summary(merged$Market.Price.CAD)
```
```{r}
# quants <- quantile(merged$Market.Price.CAD, probs=c(0.25, 0.75))
# merged <- merged %>% mutate(price_range = case_when(
#   Market.Price.CAD < quants[1] ~ "low",
#   Market.Price.CAD < quants[2] ~ "medium",
#   TRUE ~ "high"
# ))
```

```{r}
# get_price_range = function (price, year) {
#   tmp <- merged %>% filter(model_year==year)
#   qts <- quantile(tmp$Market.Price.CAD, probs=c(0.25, 0.75))
#   out = ifelse(price < qts[1], "low", ifelse(price < qts[2], "medium", "high"))
#   return(out)
# }

yearly_price_quantiles <- merged %>% group_by(model_year) %>% 
  summarise(yearly_first_q = quantile(Market.Price.CAD, probs=0.25),
            yearly_third_q = quantile(Market.Price.CAD, probs=0.75))

merged = inner_join(x=merged, y=yearly_price_quantiles)

merged = merged %>% mutate(price_range = case_when(
  Market.Price.CAD < yearly_first_q ~ 'low',
  Market.Price.CAD < yearly_third_q ~ 'medium',
  TRUE ~ 'high'
))
```

```{r}
merged %>% group_by(model_year, price_range) %>% 
  summarise(n=n()) %>% 
  arrange(model_year, price_range)
```


```{r}
ggplot(merged) +
  geom_point(aes(x=Market.Price.CAD, y=list_price)) +
  geom_abline(slope=1, intercept=0)

ggplot(merged, aes(x=mileage, y=list_price)) +
  geom_point() +
  geom_smooth(method=lm, formula=y~x, se=F) +
  facet_wrap(~price_range)
```

```{r}
ggplot(merged, aes(x=model_year, 
                   y=Market.Price.CAD, 
                   color=price_range)) +
  geom_jitter()

ggplot(merged, aes(x=model_year, 
                   y=list_price,
                   color=price_range)) +
  geom_jitter()
```